# Generated by Django 4.2.20 on 2025-04-03 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('webhook_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('flow_config', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
